apiVersion: apps/v1
kind: Deployment
metadata: 
    name: nodejs-deployment
    labels:
        app: nodejs
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nodejs
    template:
        metadata:
          labels:
            app: nodejs
        spec:
          containers:
          - name: kubernetes-demo
            image: anshuldevops/kubernetes-demo
            command: ["node", "index-db.js"]
            ports:
            - name: nodejs-port
              containerPort: 3000
            env:
              - name: MYSQL_HOST
                value: database-service
              - name: MYSQL_USER
                value: root
              - name: MYSQL_PASSWORD
                value: password
              - name: MYSQL_DATABASE
                value: helloworld